services:
  app: &services-app
    build:
      context: .
      target: development
    depends_on:
      - db
    init: true
    networks:
      default:
        aliases:
          - app.test
    volumes:
      - ./:/opt/app
      - ./tmp/devmounts/da:/srv/da
      - ./tmp/devmounts/etl:/srv/etl
      - ./tmp/devmounts/dvfiles:/srv/dvfiles

    ports:
      - 3000:3000
    restart: always

  worker:
    <<: *services-app
    command: good_job start
    depends_on:
      - db
    ports: []
  
  db:
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    image: postgres:12.2
    networks:
      default:
        aliases:
          - db.test
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./:/build:rw

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always